version: "3.8"

services:
    mssql:
      image: mcr.microsoft.com/mssql/server:latest
      environment:
        SA_PASSWORD: "1QAZ!2wsx"
        ACCEPT_EULA: "Y"
      volumes:
          - './drive:/var/opt/mssql/data'
      ports:
        - "1433:1433"